apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ include "business-profiles.fullname" . }}
  labels:
{{ include "business-profiles.labels" . | indent 4 }}
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/name: {{ include "business-profiles.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          portNumber: 50051
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value: # lua filter specification
          name: envoy.lua
          config:
            inlineCode: |
              function envoy_on_request(handle)
                handle:logWarn("DEBUG REQUEST")
              end
              function envoy_on_response(handle)
                handle:logWarn("DEBUG RESPONSE")
              end