apiVersion: v1
kind: Service
metadata:
  name: {{ include "business-profiles.fullname" . }}
  labels:
{{ include "business-profiles.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: {{ include "business-profiles.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
